### ISSUE TITLE
CPMG sequence duration scales with number of pulses

### ISSUE THREAD

**Issue by andbe91** [Labber-software/Drivers#58]
The distance between the two pi/2 pulses is not equal to the sequence duration parameters.
![image](https://user-images.githubusercontent.com/23558186/33475231-f896d9b8-d67d-11e7-9e40-7b0a67e35ed0.png)

Moreover, the distance gets longer when adding pi pulses to the sequence.
![image](https://user-images.githubusercontent.com/23558186/33475259-1a022a30-d67e-11e7-8bae-f97a719b528f.png)

Is this the intended behavior?

**Comment by simongus** [comment]
It depends if you define the pulses to be “Edge-to-edge” (checkbox in the GUI), or “Center-to-center”.  “Edge-to-edge” tries to make the qubit free evolution time between pulses correct (typically what you want), whereas “Center-to-center” assumes the pulses to be instantaneous.

**Comment by andbe91** [comment]
I see, thanks for the clarification. Closing this issue.
