### ISSUE TITLE
Bug in multi-qubit pulse generator driver

### ISSUE THREAD

**Issue by xionghn13** [Labber-software/Drivers#80]
I want to set the Sequence in the Measurement Editor by double click that item, but when I try to set a new value for it, there is an error as follows: 

> 
> 12:55:17,329:  An error occurred when sending a value to an instrument.
> 
> Instrument name: Simon's Multi-Qubit Pulse Generator (Simon's Multi-Qubit Pulse Generator) 
> Address:  
> Quantity: Sequence 
> Value: Pulse train
> 
> Error message:
> 2
> 
> Unfiltered error message:
> Traceback (most recent call last):
>   File "BaseDriver.py", line 458, in processOperation
>   File "BaseDriver.py", line 491, in performOperation
>   File "BaseDriver.py", line 756, in _performSetValue
>   File "E:\GitHubRepositories\labber-drivers\MultiQubit_PulseGenerator\MultiQubit_PulseGenerator.py", line 45, in performSetValue
>     new_type = SEQUENCES[value]
> KeyError: 2

Do you know what's going on?

**Comment by xionghn13** [comment]
if quant.name == 'Sequence':
            value = quant.getValue() 
            # create new sequence if sequence type changed
            new_type = SEQUENCES[value]

it seems that adding this line can solve this problem.

**Comment by simongus** [comment]
There is a bug in Labber's handling of setting combo-box values from the "Set Value"-dialog, will be fixed in the next release

**Comment by simongus** [comment]
Thanks for drawing our attention to the issue
